SELECT A.PRODUCT_ID,A.PRODUCT_NAME,SUM(B.AMOUNT * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A LEFT JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE SUBSTR(B.PRODUCE_DATE,1,7) = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC