-- 코드를 입력하세요
SELECT  APNT_NO,
        P.PT_NAME,
        P.PT_NO,
        D.MCDP_CD,
        DR_NAME,
        APNT_YMD
FROM PATIENT P JOIN APPOINTMENT A JOIN DOCTOR D
    ON P.PT_NO = A.PT_NO AND  A.MDDR_ID = D.DR_ID
WHERE APNT_CNCL_YN = 'N' AND SUBSTR(APNT_YMD,1,10) = '2022-04-13' AND A.MCDP_CD ='CS'
GROUP BY PT_NAME
ORDER BY APNT_YMD ASC